spring:
  datasource:
    url: jdbc:h2:mem:produtosdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 8080
